# Binding-level help for the canonical types generated by @canonical. Keeping
# descriptions here avoids changing the macro or duplicating its constructors.

@doc """
    Request(model, messages; system=nothing, tools=(), config=Config())
    Request(existing; changes...)

Describe one model request without submitting it. `messages` contains `Message`
values; a single message is accepted. `system` is text or prompt content. Tools
are `FunctionTool` or `BuiltinTool` values; a Julia function is refused, with the
fix named. Models passed to a router may use `provider:model`;
direct clients normally receive the provider's model name.

Construction validates the request. Sequences become tuples; opaque dictionaries
are shallowly shared, not deep-copied. Do not mutate them during a call. Creating
another `Request` does not retain history automatically: include earlier messages.

```jldoctest
julia> req = Request("openai:example-model", user("Hello"));

julia> Request(req; config=Config(max_tokens=64)).config.max_tokens
64
```

See also [`complete`](@ref), [`stream`](@ref), [`Message`](@ref).
""" Request

@doc """
    Response(; model, message, finish_reason, id=nothing, usage=Usage(),
             logprobs=nothing, provider_data=nothing)

Hold a provider's normalized answer. `message` must have the assistant role.
`finish_reason` is `stop`, `length`, `tool_call`, `content_filter`, or `error`.
A response can contain more than text; inspect its parts before assuming success.
`usage` preserves unreported counters as `nothing`. `provider_data` is optional
opaque provider information and is excluded from serialization by default.

```jldoctest
julia> answer = Response(model="example", message=assistant("Hello"), finish_reason="stop");

julia> text(answer)
"Hello"
```

See also [`text`](@ref), [`tool_calls`](@ref), [`Usage`](@ref), [`to_dict`](@ref).
""" Response

@doc """
    Config(; max_tokens=nothing, temperature=nothing, top_p=nothing, top_k=nothing,
           stop=(), response_format=nothing, tool_choice=nothing, reasoning=nothing,
           cache=nothing, service_tier=nothing, user_id=nothing, store=nothing,
           logprobs=nothing, extensions=nothing)
    Config(existing; changes...)

Set generation options. `nothing` means unspecified, not zero or false. Positive
limits include `max_tokens` and `top_k`; `top_p` lies in [0,1] and `temperature`
is nonnegative. Sampling numbers are stored as Float64. `stop` contains strings.
`response_format` describes JSON-object or JSON-schema output. Structured controls
use `ToolChoice`, `Reasoning`, and `CacheConfig` rather than loose dictionaries.

Provider/model support still determines whether a valid setting can be sent.
`extensions` carries explicit provider settings; it is not a guarantee of support.
`store=false` requests the provider option where supported, not a universal data
retention guarantee. Copies are shallow and perform no provider request.

See also [`Request`](@ref), [`ToolChoice`](@ref), [`Reasoning`](@ref), [`CacheConfig`](@ref).
""" Config

@doc """
    Usage(; input_tokens=nothing, output_tokens=nothing, total_tokens=...,
          cache_read_tokens=nothing, cache_write_tokens=nothing,
          reasoning_tokens=nothing, input_audio_tokens=nothing,
          output_audio_tokens=nothing)

Record nonnegative token counters. An unreported counter remains `nothing`;
reported zero remains zero. If both input and output are reported and total is
omitted, total is their checked sum. An explicitly supplied total is retained.
Counters are checked against Julia's machine `Int` range.

```jldoctest
julia> Usage(input_tokens=10, output_tokens=3).total_tokens
13

julia> Usage(input_tokens=10).total_tokens === nothing
true
```

See also [`Response`](@ref), [`estimate`](@ref).
""" Usage

@doc """
    Message(role, parts; continuation=())

Group content parts under `user`, `assistant`, `tool`, or `developer`. Prefer
`user`, `assistant`, `developer`, and `tool_message` for ordinary construction.
Messages are nonempty. Tool messages contain only tool results; user/developer
messages contain prompt content, not tool-call or reasoning protocol parts.
Sequences become tuples, with shallow sharing of nested dictionaries.

See also [`user`](@ref), [`assistant`](@ref), [`tool_message`](@ref).
""" Message

@doc """
    FunctionTool(; name, description=nothing, parameters=Dict("type"=>"object", "properties"=>Dict()))

Describe a callable operation to a provider, without storing or running its Julia
function. `parameters` is an explicit JSON Schema object, written out as in every
LM15 language; LM15 does not derive it from a Julia method. Its contents are
retained, including empty values; construction checks JSON shape, not the meaning
of arbitrary schema keywords.

See also [`tool_result`](@ref), [`tool_content`](@ref).
""" FunctionTool

for (name, signature, explanation) in (
    (:Part, "Part", "Abstract family of canonical message content. Use the existing text, media, citation, call and result variants. Application data types extend tool_value instead of inventing new wire variants."),
    (:Delta, "Delta", "Abstract family of incremental updates carried by StreamDeltaEvent. Part indices are canonical zero-based indices, not Julia array indices."),
    (:StreamEvent, "StreamEvent", "Abstract family of start, delta, end and error events. An end event, not merely end-of-input, establishes a completed streamed answer."),
    (:Tool, "Tool", "Abstract family containing FunctionTool and BuiltinTool specifications. Requests hold only these; a Julia function is refused."),
    (:LiveClientEvent, "LiveClientEvent", "Abstract family of events your application sends on a live session using send!."),
    (:LiveServerEvent, "LiveServerEvent", "Abstract family of normalized events received from a live session. Use recv or iterate a TurnView."),
    (:ContinuationState, "ContinuationState(; provider, kind, data=Dict())", "Retain opaque provider-specific replay state. Preserve it when replaying messages or parts; do not fabricate, interpret, or discard its data. Display is redacted, but explicit serialization exposes the stored data."),
    (:TextPart, "TextPart(text; continuation=())", "Store ordinary text, including the empty string. The keyword spelling is TextPart(text=...)."),
    (:ThinkingPart, "ThinkingPart(text; continuation=())", "Store provider-returned reasoning text and any replay state. Do not turn it into user instructions or invent signed reasoning state."),
    (:RefusalPart, "RefusalPart(text; continuation=())", "Store nonempty refusal text. A refusal is distinct from an ordinary textual answer and is not accepted as tool-result content."),
    (:CitationPart, "CitationPart(; url=nothing, title=nothing, text=nothing, continuation=())", "Store a citation with at least one nonempty URL, title, or text value. Provider replay support is not universal."),
    (:ToolCallPart, "ToolCallPart(; id, name, input=Dict{String,Any}(), continuation=())", "Store a proposed tool invocation. input is a string-keyed JSON object, not already-converted Julia function arguments. This object executes nothing; your code decides whether and how to run it."),
    (:ToolResultPart, "ToolResultPart(; id, content, name=nothing, is_error=false, continuation=())", "Store nonempty presentational tool output: text, media or citations, never calls or reasoning protocol parts. Prefer tool_result(call, content) to preserve the call ID and name. An empty output is one empty TextPart, not an empty content tuple."),
    (:BuiltinTool, "BuiltinTool(; name, config=nothing)", "Request a provider-hosted tool. This is not a Julia function; the provider runs it. Supported names and configuration depend on the provider, model and compatibility policy."),
    (:ToolChoice, "ToolChoice(; mode=\"auto\", allowed=(), parallel=nothing)", "Control offered tools: mode is auto, required or none. allowed names must be present in the request's tools. none forbids allowed names and a parallel setting. Provider support still applies; required is not a guarantee of a particular successful call."),
    (:Reasoning, "Reasoning(; effort, thinking_budget=nothing, summary=nothing)", "Request reasoning effort: off, minimal, low, medium, high, xhigh or max. An optional thinking_budget must be positive; summary is auto, concise or detailed. off forbids budget and summary. Model-specific mappings may reject unsupported settings."),
    (:CacheConfig, "CacheConfig(; mode=\"auto\", retention=nothing, key=nothing, prefix_until_index=nothing, prefix=nothing, resource=nothing)", "Configure prompt caching. retention is short or long; prefix is stable or history. prefix and the nonnegative prefix_until_index are mutually exclusive. resource identifies a stored cache. mode=off forbids all other cache settings. No cache is created by constructing this value."),
    (:TopLogprob, "TopLogprob(; token, logprob, bytes=nothing, token_id=nothing)", "Describe one token alternative with a finite log probability, optional byte values and provider token ID."),
    (:TokenLogprob, "TokenLogprob(; token, logprob, bytes=nothing, token_id=nothing, top=())", "Describe a generated token and its alternative TopLogprob values. These are token-level probabilities, not a confidence score for the answer's truth."),
    (:ToolCallInfo, "ToolCallInfo(; id, name, input)\n    ToolCallInfo(part::ToolCallPart)", "Hold a lightweight live-turn call description. Convert to ToolCallPart(info) where a part is needed."),
    (:InferencePricing, "InferencePricing(; input_per_million=nothing, output_per_million=nothing, cache_read_per_million=nothing, cache_write_per_million=nothing, currency=\"USD\", dimensions=nothing)", "Describe nonnegative unit prices and optional extra pricing dimensions. Unreported rates remain nothing. estimate is not an invoice and does not cover every pricing dimension."),
    (:InferenceModelInfo, "InferenceModelInfo(; input_modalities=(\"text\",), output_modalities=(\"text\",), context_window=nothing, max_output_tokens=nothing, supports_reasoning=false, reasoning_efforts=(), pricing=nothing, extensions=nothing)", "Describe reported model capabilities and optional pricing. Catalog metadata does not prove that a particular account can use every capability."),
    (:ModelOrigin, "ModelOrigin(; type=\"provider\", id=nothing, base_model=nothing, provider_data=nothing)", "Record model provenance, an optional origin ID/base model, and opaque provider information."),
    (:ModelInfo, "ModelInfo(; id, provider, api_family, aliases=(), origin=ModelOrigin(), inference=nothing, extensions=nothing)", "Describe a model for catalogs and routing. Register in ModelRegistry to resolve aliases. This metadata does not contact or validate the remote model."),
)
    doc = "    " * signature * "\n\n" * explanation
    @eval @doc $doc $name
end

for (name, mime) in ((:ImagePart,"image/png"), (:AudioPart,"audio/wav"),
                     (:VideoPart,"video/mp4"), (:DocumentPart,"application/pdf"),
                     (:BinaryPart,"application/octet-stream"))
    signature = "    $(name)(; data=nothing, url=nothing, file_id=nothing, path=nothing, media_type=\"$mime\", continuation=())"
    details = "Represent media with exactly one source. data is base64 text; use the lowercase factory to accept raw byte vectors. A path is read at request-building time, not construction. A URL/file ID is a reference, not locally fetched content. The MIME default does not inspect file bytes."
    name === :ImagePart && (details *= " ImagePart also accepts detail=nothing, low, high or auto.")
    doc = signature * "\n\n" * details
    @eval @doc $doc $name
end

for (name, signature, explanation) in (
    (:TextDelta, "TextDelta(; text=\"\", part_index=0, logprobs=())", "Append text and optional token log probabilities at a zero-based part index."),
    (:ThinkingDelta, "ThinkingDelta(; text=\"\", part_index=0)", "Append provider-returned reasoning text at a zero-based part index."),
    (:AudioDelta, "AudioDelta(; data=nothing, url=nothing, file_id=nothing, part_index=0, media_type=nothing)", "Incrementally update audio. At most one source is present. Base64 fragments are assembled before final validation; do not decode arbitrary partial fragments independently."),
    (:ImageDelta, "ImageDelta(; data=nothing, url=nothing, file_id=nothing, part_index=0, media_type=nothing)", "Incrementally update an image at a zero-based part index, with at most one data/URL/file source."),
    (:ToolCallDelta, "ToolCallDelta(; input=\"\", part_index=0, id=nothing, name=nothing)", "Append a JSON argument fragment, optionally setting the call ID/name. input is text, not an object; wait for assembly before decoding or executing a call."),
    (:CitationDelta, "CitationDelta(; text=nothing, url=nothing, title=nothing, part_index=0)", "Update citation content; at least one text, URL or title field must be present."),
    (:ContinuationDelta, "ContinuationDelta(; provider, kind, data=Dict(), part_index=nothing)", "Attach provider replay state to a part or, when part_index is nothing, to the message."),
    (:ErrorDetail, "ErrorDetail(; code, message=\"\", provider_code=nothing)", "Represent a normalized error inside an event or batch result. code must be a known canonical error code. This data object is not a thrown Exception."),
    (:StreamStartEvent, "StreamStartEvent(; id=nothing, model=nothing)", "Announce response metadata before incremental content."),
    (:StreamDeltaEvent, "StreamDeltaEvent(; delta)", "Carry one typed Delta."),
    (:StreamEndEvent, "StreamEndEvent(; finish_reason=nothing, usage=nothing, provider_data=nothing)", "Mark the end of the response with optional final reason, usage and opaque provider data."),
    (:StreamErrorEvent, "StreamErrorEvent(; error)", "Carry ErrorDetail. ResponseStream raises the corresponding failure instead of manufacturing a completed answer."),
)
    @eval @doc $("    " * signature * "\n\n" * explanation) $name
end
